spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: kimchi-domain-app-service
  profiles:
    active:
      - local
    group:
      local:
        - site-local
      dev:
        - dev

    include:
      - db
      - secret


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}

jwt:
  secretKey: 92Tl89VinL7D2VjA
  access:
    expiration: 3600000
    header: Authorization

  refresh:
    expiration: 1209600000
    header: Authorization-refresh
